### ISSUE TITLE
Amazing plugin!

### ISSUE THREAD

**Issue by trevordmiller** [timrwood/grunt-ipsum#3]
Hey @timrwood,

First off, I just wanted to let you know that this plugin is absolutely amazing. We are going to start using it on my team.

Secondly, would you be able to add support for real lorem ipsum? Maybe options for random headers, paragraphs, and sentences? That would be legit.

Great work man.

**Comment by timrwood** [comment]
Ah yes, I don't know how I missed that. I'll see if I can include multiple sources for ipsum text, like the ones here http://meettheipsums.com/.

**Comment by trevordmiller** [comment]
That would be awesome. Please let me know if there is an update. Thanks!

**Comment by trevordmiller** [comment]
Hey @timrwood,

Have there been any updates with this? My team and I are absolutely loving this plugin and have been using it with all of our projects to create a fake JSON API until the back-end developers are ready with the real API.

This issue is the only issue we have. If lorem ipsum could be added (words/link text, headings, sentences, and paragraphs) and incorporated into the ipsum methods in the same way that something like `{%= ipsum.name %}` generates a random name, we could have prototypes that simulate varying options input by a CMS. Currently, we are hard coding this. For example, here is our menu with links and sub-links:
![screen shot 2014-09-23 at 1 19 54 pm](https://cloud.githubusercontent.com/assets/5497885/4378387/b0017b3e-4357-11e4-8461-7f95c5f22432.png)

As you can see, we are able to generate a random amount of sub-links (drop-down items) using something like:

```
repetitions: {
            'projectMenu.links': 6,
            'projectMenu.links.sublinks': [1, 10]
}
```

...if we could also randomize the text with lorem ipsum, that would be amazing!

Thank you for creating such a wonderful plugin. Please let me know when this feature has been released.

**Comment by trevordmiller** [comment]
@timrwood: Just following up...any updates?

**Comment by trevordmiller** [comment]
@timrwood It looks like the Faker package you are using already has built in lorem ipsum support for words, sentence, sentences, paragraph, paragraphs; can this be added to the `grunt-ipsum` plugin?

_screenshot_
![screen shot 2014-09-30 at 3 43 16 pm](https://cloud.githubusercontent.com/assets/5497885/4467020/3f349708-48eb-11e4-8d26-83a6007006c3.png)

https://github.com/Marak/Faker.js

**Comment by trevordmiller** [comment]
@timrwood: bump

**Comment by timrwood** [comment]
Sorry, I haven't had time to add this functionality yet.

If you want, you can add a PR that adds this in.

I think it would be pretty easy to add a couple lines [after this one](https://github.com/timrwood/grunt-ipsum/blob/c992f502a234b530477659ea70406af90856d0ee/lib/data.js#L42) for `words`, `sentence`, `sentences`, `paragraph` and `paragraphs`, then [add those properties to the tests](https://github.com/timrwood/grunt-ipsum/blob/c992f502a234b530477659ea70406af90856d0ee/test/tests/faker.js#L86), [fixture data](https://github.com/timrwood/grunt-ipsum/blob/c992f502a234b530477659ea70406af90856d0ee/test/tasks/faker.js#L75), and [the docs](https://github.com/timrwood/grunt-ipsum/blob/master/README.md#images)

**Comment by trevordmiller** [comment]
@timrwood: No worries. Thanks for getting back to me.
